name: "Build"
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: DeterminateSystems/magic-nix-cache-action@v2
      - run: nix build .#dockerImage -o petms-website-docker
      - name: Archive docker image
        uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: petms-website-docker
